// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilzrakdidphizbglpayu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsenJha2RpZHBoaXpiZ2xwYXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTM0NTQsImV4cCI6MjA1OTM2OTQ1NH0.BSGHfOr5CcjkaLJEv9HFWs3YffxOU7RNa3j_F71Mx3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);